### ISSUE TITLE
not available on official Flutter Pub

### ISSUE THREAD

**Issue by drchanjy** [Vonage-Community/sample-video-flutter-app#1]

**Comment by drchanjy** [comment]
https://pub.dev/packages/vonage
there is one but doesn't seem to be an official one

**Comment by anilchoudhary84** [comment]
is there anything from Vonage posted on Flutter Pub?

**Comment by devwithzachary** [comment]
Hello, This project is an example application that shows you how to use the native Android and iOS libraries within a Flutter application. At this time we do not have a flutter SDK/Package. Thank you
