### ISSUE TITLE
Toggle audio error

### ISSUE THREAD

**Issue by jttuboi** [Vonage-Community/sample-video-flutter-app#2]
In the file one_to_one_video.dart in line 104, it is written `await platformMethodChannel.invokeMethod('publishAudio', params);` but the correct is `await platformMethodChannel.invokeMethod('toggleAudio', params);`.

**Comment by devwithzachary** [comment]
Thank you for reporting this, I've fixed it against https://github.com/Vonage-Community/sample-video-flutter-app/commit/b6c47cd3222bd0a02418d641cd4a173b93d84641
