### ISSUE TITLE
How to end the session

### ISSUE THREAD

**Issue by swarupbhc** [Vonage-Community/sample-video-flutter-app#3]
There is a function to init a session "initSession", but How can I end a session?
I can't find any function or method to end the session manually, please help me with a solution.

**Comment by devwithzachary** [comment]
Hi! 
You can do this using the [Session.disconnect()](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.html#disconnect--) method. This will disconnect you from that session. 

So you could create a method in the Android/iOS native code to call this which can then be called from the Flutter code, in the same way that the initSession is.

**Comment by swarupbhc** [comment]
Thank you @devwithzachary
