### ISSUE TITLE
How can I stop the camera in multi video?

### ISSUE THREAD

**Issue by bizk-sato** [Vonage-Community/sample-video-flutter-app#5]
I use `session.disconnect()` and then delete `MultiVideo` component from view to finish the call.
Even after that the camera is still on for android emulator.
So if I make another call, there occurs an error because it tries to start camera which is already on.

So when I finish calling, I want to stop the camera.
Is there any way to do this?

**Comment by devwithzachary** [comment]
The way to do this is with the [PublisherKit.onStop()](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/PublisherKit.html#onStop--) method. This releases the camera.

**Comment by bizk-sato** [comment]
@devwithzachary Solved it. Thank you.
